DROP TABLE Dane CASCADE CONSTRAINTS;
DROP TABLE Pracownicy CASCADE CONSTRAINTS;
DROP TABLE Produkty CASCADE CONSTRAINTS;
DROP TABLE Miejsce CASCADE CONSTRAINTS;
DROP TABLE Bilet CASCADE CONSTRAINTS;
DROP TABLE Film CASCADE CONSTRAINTS;
DROP TABLE Sala CASCADE CONSTRAINTS;
DROP TABLE Seans CASCADE CONSTRAINTS;
DROP TABLE Klient CASCADE CONSTRAINTS;
DROP TABLE Klient_Produkty CASCADE CONSTRAINTS;
DROP TABLE Dane_Film CASCADE CONSTRAINTS;

--usuwanie sekwencji
DROP SEQUENCE dane_sequence;
DROP SEQUENCE pracownicy_sequence;
DROP SEQUENCE produkty_sequence;
DROP SEQUENCE miejsce_sequence;
DROP SEQUENCE bilet_sequence;
DROP SEQUENCE film_sequence;
DROP SEQUENCE sala_sequence;
DROP SEQUENCE seans_sequence;
DROP SEQUENCE klient_sequence;
DROP SEQUENCE klient_produkty_sequence;
DROP SEQUENCE dane_film_sequence;

--usuwanie wyzwalaczy
DROP TRIGGER PRACOWNICY_TRIGGER;
DROP TRIGGER DANE_TRIGGER;
DROP TRIGGER DANE_FILM_TRIGGER;
DROP TRIGGER PRODUKTY_TRIGGER;
DROP TRIGGER SEANS_TRIGGER;

--usuniecie widoku
drop view seans_view;
drop view dane_view;
drop view sala_view;
--usuniecie procedur
drop procedure PODWYZKA_PRACOWNIKA;
drop procedure ZMIANA_CEN_PRODUKTOW;
drop procedure MODYFIKACJA_DANYCH_W_TABELI_DANE;
drop procedure MODYFIKACJA_DANYCH_W_TABELI_PRACOWNICY;