$CLS
PROMPT Menu:
PROMPT 1. CREATE_ALL 
PROMPT 2. DROP_ALL 
PROMPT 3. INSERT_ALL
PROMPT 4. DELETE_ALL
PROMPT 5. SELECT
PROMPT 6. PROCEDURES
PROMPT 7. MODIFY
PROMPT 8. WYWOLANIA_PROCEDUR
PROMPT 0. KONIEC
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT '?: '
$CLS
PROMPT wybor = &wybor
@&wybor\main.sql &wybor
PROMPT 
PROMPT # Wcisnij ENTER #
PAUSE
@main.sql