SET ECHO ON
EXECUTE PODWYZKA_PRACOWNIKA(155,'KASJER');
EXECUTE ZMIANA_CEN_PRODUKTOW(1,1,'2,0');
EXECUTE MODYFIKACJA_DANYCH_W_TABELI_DANE(1,1,'Piotr');
EXECUTE MODYFIKACJA_DANYCH_W_TABELI_PRACOWNICY(1,1,1789);
SET ECHO OFF